import ConfigParser as cfg

# autogenerated
def load_paths(paths_config_filepath='/Users/babasarala/repos/earl/config/path_config.ini'):
	''' parses the config file containing all important paths'''

	cfg_parser = cfg.SafeConfigParser()
	cfg_parser.read(paths_config_filepath)
	paths = {}
	paths_options = cfg_parser.options('PATHS')
	for option in paths_options:
		paths[option] = cfg_parser.get('PATHS',option)
	return paths
